disabled_rules:
  - control_statement
  - cyclomatic_complexity

opt_in_rules:
  - empty_count

excluded:
  - Carthage
  - Pods
  - ThisDateInHistoryTests
  - ThisDateInHistoryUITests

force_cast: warning 
force_try:
  severity: warning 

line_length:
  warning: 120
  error: 300
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 1200

function_body_length:
  warning: 50
  error: 200

trailing_whitespace:
  ignores_empty_lines: true

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50
  excluded: iPhone

identifier_name:
  min_length:
    error: 3 # only error
  excluded: # excluded via string array
    - id
    - ID
    - URL
    - GlobalAPIKey

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)